######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 12 19:38:28 2014
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += buttons.h draw.h ffft.h lcd.h menu.h settings.h uart.h
SOURCES += buttons.c draw.c lcd.c main.c menu.c settings.c uart.c

OTHER_FILES += \
    Makefile \
    ffft.S
